In [1]:
import tensorflow as tf
import numpy as np

In [2]:
num_points = 2000
vectors_set = []
for i in xrange(num_points):
    if np.random.random() > 0.5 :
        vectors_set.append([np.random.normal(0.0, 0.9), np.random.normal(0.0,0.9)])
    else:
        vectors_set.append([np.random.normal(3.0, 0.5), np.random.normal(1.0,0.5)])

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df = pd.DataFrame({"x":[v[0] for v in vectors_set],"y":[v[1] for v in vectors_set]})
sns.lmplot("x","y",data=df,fit_reg=False,size=6)
plt.show()

//anaconda/lib/python2.7/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
//anaconda/lib/python2.7/site-packages/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':


In [4]:
vectors = tf.constant(vectors_set)
k = 4
centroides = tf.Variable(tf.slice(tf.random_shuffle(vectors),[0,0],[k,-1]))
expanded_vectors = tf.expand_dims(vectors,0) #vectors : 2
expanded_centroides = tf.expand_dims(centroides,1)
assignments = tf.argmin(tf.reduce_sum(tf.square(tf.subtract(expanded_vectors,expanded_centroides)),2),0)
means = tf.concat([tf.reduce_mean(tf.gather(vectors,tf.reshape(tf.where(tf.equal(assignments,c)),[1,-1])), reduction_indices=[1]) for c in xrange(k)],0)

update_centroides = tf.assign(centroides, means)
init_op = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init_op)

for step in xrange(100):
    _, centroid_values, assignment_values = sess.run([update_centroides, centroides, assignments])
    print centroid_values
    

[[ 0.4770982  -1.08021951]
 [-0.46619618  0.16830321]
 [ 2.02368355  0.26624891]
 [ 3.0519855   1.1572696 ]]
[[ 0.340812   -0.97271323]
 [-0.48395741  0.30925843]
 [ 1.86041903  0.40871152]
 [ 3.09036827  1.09666669]]
[[ 0.22738956 -0.92912209]
 [-0.51549757  0.39001617]
 [ 1.70968068  0.47348344]
 [ 3.09522223  1.0676527 ]]
[[ 0.13992828 -0.89850515]
 [-0.56857479  0.45113888]
 [ 1.56738675  0.48298627]
 [ 3.08867598  1.05779529]]
[[ 0.07375605 -0.89242202]
 [-0.60872883  0.48215526]
 [ 1.45210493  0.43546885]
 [ 3.07721472  1.05276752]]
[[ 0.01579508 -0.89730972]
 [-0.62227535  0.51419777]
 [ 1.35259843  0.39719477]
 [ 3.06477952  1.04586899]]
[[-0.04063308 -0.90303099]
 [-0.65024173  0.53548336]
 [ 1.23324299  0.32706082]
 [ 3.04615593  1.04088199]]
[[-0.10943067 -0.90939981]
 [-0.67301744  0.55705148]
 [ 1.14074588  0.25482106]
 [ 3.03215432  1.03778386]]
[[-0.18351422 -0.92542958]
 [-0.67877609  0.58323693]
 [ 1.06115603  0.20376848]
 [ 3.02280092  1.03171957]]
[[-0.23483762 -0.93

In [5]:
data = {"x":[], "y":[], "cluster":[]}

for i in xrange(len(assignment_values)):
    data["x"].append(vectors_set[i][0])
    data["y"].append(vectors_set[i][1])
    data["cluster"].append(assignment_values[i])
    
df = pd.DataFrame(data)
sns.lmplot("x","y", data=df, fit_reg=False, size=6, hue="cluster", legend=False)
plt.show()