#Numpy

In [1]:
import numpy

In [2]:
numpy.asarray([[1., 2], [3, 4], [5, 6]])

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [3]:
numpy.asarray([[1., 2], [3, 4], [5, 6]]).shape

(3L, 2L)

In [4]:
numpy.asarray([[1., 2], [3, 4], [5, 6]])[2, 0]

5.0

In [6]:
a = numpy.asarray([1.0, 2.0, 3.0])
b = 2.0
a * b

array([ 2.,  4.,  6.])

#Algebra

In [7]:
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x, y], z)

Using gpu device 0: GeForce GTX TITAN X


In [8]:
f(2, 3)

array(5.0)

In [9]:
f(16.3, 12.1)

array(28.4)

#Step1

In [11]:
x = T.dscalar('x')
y = T.dscalar('y')

In [12]:
type(x)

theano.tensor.var.TensorVariable

In [13]:
x.type

TensorType(float64, scalar)

In [14]:
T.dscalar

TensorType(float64, scalar)

In [15]:
x.type is T.dscalar

True

#Step2

In [16]:
z = x + y

In [17]:
from theano import pp
print pp(z)

(x + y)


#Step3

In [18]:
f = function([x, y], z)

In [19]:
import theano.tensor as T
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
z.eval({x : 16.3, y : 12.1})

array(28.4)

In [21]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)

In [22]:
f([[1, 2], [3, 4]], [[10, 20], [30, 40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

In [23]:
import numpy
f(numpy.array([[1, 2], [3, 4]]), numpy.array([[10, 20], [30, 40]]))

array([[ 11.,  22.],
       [ 33.,  44.]])

In [24]:
import theano
a = theano.tensor.vector() # declare variable
out = a + a ** 10               # build symbolic expression
f = theano.function([a], out)   # compile function
print f([0, 1, 2])  # prints `array([0, 2, 1026])`

[    0.     2.  1026.]


In [25]:
a = theano.tensor.vector()  # declare variable
b = theano.tensor.vector()  # declare variable
out = a ** 2 + b ** 2 + 2 * a * b  # build symbolic expression
f = theano.function([a, b], out)   # compile function
print(f([1, 2], [4, 5]))  # prints [ 25.  49.]

[ 25.  49.]


DEBUG: nvcc STDOUT mod.cu
   C:/Users/nuri/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.9-64/tmpmxhr1x/14fe0c0d3d392da24f4b5198486428df.lib ���̺귯�� �� C:/Users/nuri/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.9-64/tmpmxhr1x/14fe0c0d3d392da24f4b5198486428df.exp ��ü�� �����ϰ� �ֽ��ϴ�.



#Basic Example

##Tensor

http://deeplearning.net/software/theano/library/tensor/basic.html#libdoc-basic-tensor

##로지스틱 곡선

In [26]:
x = T.dmatrix('x')
s = 1 / (1 + T.exp(-x))    
logistic = function([x], s)
logistic([[0, 1], [-1, -2]])

array([[ 0.5       ,  0.73105858],
       [ 0.26894142,  0.11920292]])

In [27]:
s2 = (1 + T.tanh(x / 2)) / 2
logistic2 = function([x], s2)
logistic2([[0, 1], [-1, -2]])

array([[ 0.5       ,  0.73105858],
       [ 0.26894142,  0.11920292]])

##Computing More than one Thing at the Same Time

In [28]:
a, b = T.dmatrices('a', 'b')
diff = a - b
abs_diff = abs(diff)
diff_squared = diff**2
f = function([a, b], [diff, abs_diff, diff_squared])

In [29]:
f([[1, 1], [1, 1]], [[0, 1], [2, 3]])

[array([[ 1.,  0.],
        [-1., -2.]]), array([[ 1.,  0.],
        [ 1.,  2.]]), array([[ 1.,  0.],
        [ 1.,  4.]])]

##Setting a Default Value for an Argument

In [31]:
from theano import Param
x, y = T.dscalars('x', 'y')
z = x + y
f = function([x, Param(y, default=1)], z)
f(33)

array(34.0)

In [32]:
f(33, 2)

array(35.0)

#Default Values

In [34]:
x, y, w = T.dscalars('x', 'y', 'w')
z = (x + y) * w
f = function([x, Param(y, default=1), Param(w, default=2, name='w_by_name')], z)
f(33)

array(68.0)

In [35]:
f(33, 2)

array(70.0)

In [36]:
f(33, w_by_name=1)

array(34.0)

In [37]:
f(33, w_by_name=1, y=0)

array(33.0)

##Using Shared Variables

In [39]:
from theano import shared
state = shared(0)
inc = T.iscalar('inc')
accumulator = function([inc], state, updates=[(state, state+inc)])

In [40]:
state.get_value()

array(0)

In [41]:
accumulator(1)

array(0)

In [42]:
accumulator(300)

array(1)

In [43]:
state.get_value()

array(301)

In [45]:
state.set_value(-1)
accumulator(3)

array(-1)

In [46]:
state.get_value()

array(2)

In [48]:
decrementor = function([inc], state, updates=[(state, state-inc)])
decrementor(2)

array(2)

In [49]:
state.get_value()

array(0)

In [50]:
fn_of_state = state * 2 + inc
# The type of foo must match the shared variable we are replacing
# with the ``givens``
foo = T.scalar(dtype=state.dtype)
skip_shared = function([inc, foo], fn_of_state, givens=[(state, foo)])
skip_shared(1, 3)  # we're using 3 for the state, not state.value

array(7)

In [51]:
state.get_value()

array(0)

##Brief Example

In [52]:
from theano.tensor.shared_randomstreams import RandomStreams
from theano import function
srng = RandomStreams(seed=234)
rv_u = srng.uniform((2,2))
rv_n = srng.normal((2,2))
f = function([], rv_u)
g = function([], rv_n, no_default_updates=True)    #Not updating rv_n.rng
nearly_zeros = function([], rv_u + rv_u - 2 * rv_u)

In [53]:
f_val0 = f()
f_val1 = f()  #different numbers from f_val0

In [54]:
g_val0 = g()  # different numbers from f_val0 and f_val1
g_val1 = g()  # same numbers as g_val0!

In [55]:
nearly_zeros = function([], rv_u + rv_u - 2 * rv_u)

##Seeding Streams

In [56]:
rng_val = rv_u.rng.get_value(borrow=True)   # Get the rng for rv_u
rng_val.seed(89234)                         # seeds the generator
rv_u.rng.set_value(rng_val, borrow=True)    # Assign back seeded rng

In [57]:
srng.seed(902340)  # seeds rv_u and rv_n with different seeds each

##Sharing Streams Between Functions

In [58]:
state_after_v0 = rv_u.rng.get_value().get_state()
nearly_zeros()       # this affects rv_u's generator
v1 = f()
rng = rv_u.rng.get_value(borrow=True)
rng.set_state(state_after_v0)
rv_u.rng.set_value(rng, borrow=True)
v2 = f()             # v2 != v1
v3 = f()             # v3 == v1

##Copying Random State Between Theano Graphs

In [59]:
import theano
import numpy
import theano.tensor as T
from theano.sandbox.rng_mrg import MRG_RandomStreams
from theano.tensor.shared_randomstreams import RandomStreams

class Graph():
    def __init__(self, seed=123):
        self.rng = RandomStreams(seed)
        self.y = self.rng.uniform(size=(1,))

g1 = Graph(seed=123)
f1 = theano.function([], g1.y)

g2 = Graph(seed=987)
f2 = theano.function([], g2.y)

print 'By default, the two functions are out of sync.'
print 'f1() returns ', f1()
print 'f2() returns ', f2()

def copy_random_state(g1, g2):
    if isinstance(g1.rng, MRG_RandomStreams):
        g2.rng.rstate = g1.rng.rstate
    for (su1, su2) in zip(g1.rng.state_updates, g2.rng.state_updates):
        su2[0].set_value(su1[0].get_value())

print 'We now copy the state of the theano random number generators.'
copy_random_state(g1, g2)
print 'f1() returns ', f1()
print 'f2() returns ', f2()

By default, the two functions are out of sync.
f1() returns  [ 0.72803009]
f2() returns  [ 0.55056769]
We now copy the state of the theano random number generators.
f1() returns  [ 0.59044123]
f2() returns  [ 0.59044123]


##A Real Example: Logistic Regression

In [2]:
import numpy
import theano
import theano.tensor as T
rng = numpy.random

N = 400
feats = 784
D = (rng.randn(N, feats), rng.randint(size=N, low=0, high=2))
training_steps = 10000

# Declare Theano symbolic variables
x = T.matrix("x")
y = T.vector("y")
w = theano.shared(rng.randn(feats), name="w")
b = theano.shared(0., name="b")
print "Initial model:"
print w.get_value(), b.get_value()

# Construct Theano expression graph
p_1 = 1 / (1 + T.exp(-T.dot(x, w) - b))   # Probability that target = 1
prediction = p_1 > 0.5                    # The prediction thresholded
xent = -y * T.log(p_1) - (1-y) * T.log(1-p_1) # Cross-entropy loss function
cost = xent.mean() + 0.01 * (w ** 2).sum()# The cost to minimize
gw, gb = T.grad(cost, [w, b])             # Compute the gradient of the cost
                                          # (we shall return to this in a
                                          # following section of this tutorial)

# Compile
train = theano.function(
          allow_input_downcast=True,
          inputs=[x,y],
          outputs=[prediction, xent],
          updates=((w, w - 0.1 * gw), (b, b - 0.1 * gb)))
predict = theano.function(inputs=[x], outputs=prediction, allow_input_downcast=True,)

for i in range(training_steps):
    pred, err = train(D[0], D[1])


print "Final model:"
print w.get_value(), b.get_value()
print "target values for D:", D[1]
print "prediction on D:", predict(D[0])

 Initial model:
[  4.50777963e-01  -9.59009294e-02   8.40004174e-03   7.85963651e-01
   1.77518910e+00   5.71788918e-01  -9.48207695e-01   1.26680600e+00
   9.19910619e-01  -4.92997009e-01  -2.38742364e-01  -6.13871694e-02
  -1.22306760e+00   2.84916074e-01  -6.79788498e-01   9.89164824e-01
  -9.85464406e-01  -3.46563223e-01  -1.19378848e+00   1.16695368e+00
  -5.18670810e-01  -1.77892020e+00  -2.61933225e-01  -3.92883311e-01
   2.80774697e-01  -2.72333026e-01  -7.59301466e-02   1.26383207e-02
   8.38573509e-01   7.77308150e-01   5.26298633e-02   7.16793028e-01
   2.96076612e-01   1.19518544e+00   2.24481255e-01   1.28567313e+00
   1.20193723e-01  -1.47818733e-01   1.09512198e-01   1.34012420e+00
   7.34299483e-01  -2.45885843e-01  -1.07467214e+00   1.14394356e-01
  -1.12265582e+00   4.36133957e-02   2.49191570e-01   8.48152042e-02
  -1.80973558e-01  -2.28094326e-01  -1.59386043e-01  -1.09733299e+00
  -3.04443931e-01  -5.44803647e-01   7.83357983e-01  -1.58066532e+00
   3.08574218e-01 